#用例方法和名称
testCase1 (case_darenquan.MyTest): 达人圈.发布达人圈
testCase2 (case_darenquan.MyTest): 达人圈.获取个人发布内容
testCase3 (case_darenquan.MyTest): 达人圈.点赞内容
testCase4 (case_darenquan.MyTest): 达人圈.收藏内容
testCase5 (case_darenquan.MyTest): 达人圈.关注他人
testCase6 (case_darenquan.MyTest): 达人圈.查看已关注的用户信息
testCase7 (case_darenquan.MyTest): 达人圈.查看获赞和收藏数
testCase8 (case_darenquan.MyTest): 达人圈.取消点赞
testCase9 (case_darenquan.MyTest): 达人圈.取消收藏
testCase10 (case_darenquan.MyTest): 达人圈.取消关注
testCase11 (case_darenquan.MyTest): 达人圈.发表评论
testCase12 (case_darenquan.MyTest): 达人圈.删除发布内容
testCase1 (case_goodstrade.MyTest): 商品交易.确认订单信息
testCase2 (case_goodstrade.MyTest): 商品交易.提交订单成功未支付
testCase3 (case_goodstrade.MyTest): 商品交易.使用余额支付成功
testCase4 (case_goodstrade.MyTest): 商品交易.订单取消成功
testCase1 (case_shipping_address.MyTest): 收货地址管理.新增地址
testCase2 (case_shipping_address.MyTest): 收货地址管理.查看地址
testCase3 (case_shipping_address.MyTest): 收货地址管理.设置默认地址
testCase4 (case_shipping_address.MyTest): 收货地址管理.编辑地址
testCase5 (case_shipping_address.MyTest): 收货地址管理.删除地址
testCase1 (case_shopping_cart.MyTest): 购物车操作.商品加入购物车
testCase2 (case_shopping_cart.MyTest): 购物车操作.查看购物车信息
testCase3 (case_shopping_cart.MyTest): 购物车操作.增加商品数量
testCase4 (case_shopping_cart.MyTest): 购物车操作.删除购物车商品
testCase1 (case_useraction.MyTest): 用户操作.首页信息展示
testCase2 (case_useraction.MyTest): 用户操作.店铺信息展示
testCase3 (case_useraction.MyTest): 用户操作.消息通知成功
testCase4 (case_useraction.MyTest): 用户操作.个人信息展示